version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/
hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: root
      timeout: 1200
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 60
  ValidateService:
    - location: scripts/cleanup.sh
      runas: root
      timeout: 60